"""Add Product model migration

Revision ID: 4dd726ce30f9
Revises: 573c6ee6e4bf
Create Date: 2025-02-17 22:14:54.027110

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


import importlib
import warnings
from app.core.utils.loader import dynamic_import


custom_models = dynamic_import("custom/models", "custom.models")


for model_name, module in custom_models.items():
    try:
        importlib.import_module(f"custom.models.{model_name}")
    except Exception as e:
        warnings.warn(f"Could not load custom model `{model_name}`: {e}")


revision = '4dd726ce30f9'
down_revision = '573c6ee6e4bf'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
