"""Add Translation model

Revision ID: 7649cc2cc281
Revises: 9c9e55035361
Create Date: 2025-02-18 12:36:59.186503

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


import importlib
import warnings
from app.core.utils.loader import dynamic_import


custom_models = dynamic_import("custom/models", "custom.models")


for model_name, module in custom_models.items():
    try:
        importlib.import_module(f"custom.models.{model_name}")
    except Exception as e:
        warnings.warn(f"Could not load custom model `{model_name}`: {e}")


revision = '7649cc2cc281'
down_revision = '9c9e55035361'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation',
    sa.Column('language_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_key'), 'translation', ['key'], unique=False)
    op.create_index(op.f('ix_translation_language_code'), 'translation', ['language_code'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_language_code'), table_name='translation')
    op.drop_index(op.f('ix_translation_key'), table_name='translation')
    op.drop_table('translation')
    # ### end Alembic commands ###
