"""Add preferred_language to users

Revision ID: 9c9e55035361
Revises: 4dd726ce30f9
Create Date: 2025-02-18 12:34:21.350291

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


import importlib
import warnings
from app.core.utils.loader import dynamic_import


custom_models = dynamic_import("custom/models", "custom.models")


for model_name, module in custom_models.items():
    try:
        importlib.import_module(f"custom.models.{model_name}")
    except Exception as e:
        warnings.warn(f"Could not load custom model `{model_name}`: {e}")


revision = '9c9e55035361'
down_revision = '4dd726ce30f9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('preferred_language', sa.String(length=5), server_default=sa.text("'en'"), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'preferred_language')
    # ### end Alembic commands ###
