"""Fully remove Item model and references

Revision ID: a932af467a8a
Revises: 3dedc0e18d0d
Create Date: 2025-02-06 00:19:53.789097

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a932af467a8a'
down_revision = '3dedc0e18d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
